.PHONY: all clean test

all:
	cd dates && make all
	cd rates && make all
	cd stdext && make all

clean:
	cd dates && make clean
	cd rates && make clean
	cd stdext && make clean

test:
	cd dates && make test
	cd rates && make test
	cd stdext && make test
	